services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  minio:
    image: 'minio/minio:latest'
    entrypoint: sh -c 'mkdir -p /data && minio server --address :9000 --console-address :9001 /data'
    environment:
      - 'MINIO_ROOT_USER=minioadmin'
      - 'MINIO_ROOT_PASSWORD=minioadmin'
    ports:
      - '9997:9001'
      - '9996:9000'
