spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: shopdoorskd@gmail.com
    password: dtjg kbnp htqd hdza
    properties.mail.smtp.from: shopdoorskd@gmail.com
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  jpa:
    open-in-view: true
    generate-ddl: true
  main:
    banner-mode: off

minio:
  url: http://127.0.0.1
  accessKey: minioadmin
  secretKey: minioadmin
  port: 9996
  secure: false
  partSize: 5242880
  imgBucket: image
  imgProductPath: products/
  imgProfilePath: profiles/
  defaultProfileImgPath: profiles/unknownUser.svg